image: jakzal/phpqa:php8.1

before_script:
  - composer install

cache:
  paths:
    - vendor/
stages:
  - SecurityChecker
  - CodingStandards
  - UnitTests

security-checker:
  stage: SecurityChecker
  script:
    - local-php-security-checker composer.lock
  allow_failure: false # true

phpcs:
  stage: CodingStandards
  script:
    - phpcs -v --standard=PSR2 --ignore=./src/Kernel.php ./src
  allow_failure: false

phpstan:
  stage: CodingStandards
  script:
    - phpstan analyse ./src
  allow_failure: false

phpunit:
  image: php:8.1-apache
  stage: UnitTests
  services:
    - name: mysql:5.7
      alias: mysql
  variables:
    MYSQL_ROOT_PASSWORD: KNOD
    MYSQL_DATABASE: KNOD
    MYSQL_USER: KNOD
    MYSQL_PASSWORD: KNOD
    DATABASE_URL: "mysql://KNOD:KNOD@mysql:3306/KNOD"
  before_script:
    - apt-get update && apt-get install -y git libzip-dev npm wget
    - curl -sSk https://getcomposer.org/installer | php -- --disable-tls && mv composer.phar /usr/local/bin/composer
    - docker-php-ext-install mysqli pdo pdo_mysql zip
    - wget https://get.symfony.com/cli/installer -O - | bash
    - mv /root/.symfony/bin/symfony /usr/local/bin/symfony
    - npm install -g newman
    - composer install
    - mv ./config/jwt/private_test.pem ./config/jwt/private.pem && mv ./config/jwt/public_test.pem ./config/jwt/public.pem
    - symfony server:ca:install && symfony serve -d
    - php bin/console doctrine:database:drop --force --env=test
    - php bin/console doctrine:database:create --env=test
#    - php bin/console doctrine:migrations:migrate --env=test --no-interaction

  cache:
    paths:
      - vendor/
  script:
    - php vendor/bin/phpunit
#    - newman run ./postman/user.postman_collection.json -e ./postman/postman_environment.json
  allow_failure: false
