image: jakzal/phpqa:php8.0

before_script:
  - composer install

cache:
  paths:
    - vendor/
stages:
  - SecurityChecker
  - CodingStandards
  - UnitTests

security-checker:
  stage: SecurityChecker
  script:
    - local-php-security-checker composer.lock
  allow_failure: false # true

phpcs:
  stage: CodingStandards
  script:
    - phpcs -v --standard=PSR2 --ignore=./src/Kernel.php ./src
  allow_failure: false

phpstan:
  stage: CodingStandards
  script:
    - phpstan analyse ./src
  allow_failure: false

phpunit:
  image: php:8.0-apache
  stage: UnitTests
  services:
    - name: mysql:5.7
      alias: mysql
  variables:
    MYSQL_ROOT_PASSWORD: KNOD
    MYSQL_DATABASE: KNOD
    MYSQL_USER: KNOD
    MYSQL_PASSWORD: KNOD
    DATABASE_URL: "mysql://KNOD:KNOD@mysql:3306/KNOD"
  before_script:
    - apt-get update && apt-get install -y git libzip-dev
    - curl -sSk https://getcomposer.org/installer | php -- --disable-tls && mv composer.phar /usr/local/bin/composer
    - docker-php-ext-install mysqli pdo pdo_mysql zip
    - php bin/console doctrine:database:drop --force --env=test
    - php bin/console doctrine:database:create --env=test
    # - php bin/console doctrine:migrations:migrate --env=test --no-interaction
  script:
    - php vendor/bin/phpunit
  allow_failure: false
