version: "3.7"
services:
  database:
    image: "mysql:latest"
    environment:
      MYSQL_ROOT_PASSWORD: KNOD
      MYSQL_DATABASE: KNOD
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
  mailer:
    image: schickling/mailcatcher
    ports: [ "1025", "1080" ]

volumes:
  ###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
